### ISSUE TITLE
Show hide does not work

### ISSUE THREAD

**Issue by dvdobrovolskiy** [joseshiru/p-loading#5]
Cannot understand this

```
$('body').ploading({ action: 'show' });
/* some code in between*/
$('body').ploading({ action: 'hide' });
```

will not show it on modern chrome and mozilla
but

```
$('body').ploading({ action: 'show' });
/* some code in between*/
//$('body').ploading({ action: 'hide' });
```
Leaves ploading overlay over the screen

in between I have this
```
xhttp = new XMLHttpRequest();
            xhttp.onreadystatechange = function () {
                var a;
                if (xhttp.readyState === 4 && xhttp.status === 200) {
                    a = document.createElement('a');
                    a.href = window.URL.createObjectURL(xhttp.response);
                    a.download = "test.zip";
                    a.style.display = 'none';
                    document.body.appendChild(a);
                    a.click();
                    a.parentElement.removeChild(a);
                }
            };
```
            xhttp.open("POST", "Form/Download");
            xhttp.setRequestHeader("Content-Type", "application/json");
            xhttp.dataType = "json";
            xhttp.responseType = 'blob';
            xhttp.send(JSON.stringify(organization));

**Comment by joseshiru** [comment]
Hi,

I see that the problem is that you're calling the show and hide action one after the other. So, basically you will never see the loading mask as few milliseconds after you displayed the mask, you're calling the hide action.

Solution : you're doing an Ajax request, so please try to call  the hide mask({action :'hide'}) action inside the Done callback of your Ajax request. (that's what I think you want to do it)

In this way you will execute the hide mask action only after your Ajax request is done.

Hope this helped you.

8 May 2017 7:13 p.m. wrote on Dima <notifications@github.com>:

Cannot understand this

$('body').ploading({ action: 'show' });
/* some code in between*/
$('body').ploading({ action: 'hide' });


will not show it on modern chrome and mozilla
but

$('body').ploading({ action: 'show' });
/* some code in between*/
//$('body').ploading({ action: 'hide' });


Leaves ploading overlay over the screen

in between I have this

xhttp = new XMLHttpRequest();
            xhttp.onreadystatechange = function () {
                var a;
                if (xhttp.readyState === 4 && xhttp.status === 200) {
                    a = document.createElement('a');
                    a.href = window.URL.createObjectURL(xhttp.response);
                    a.download = "test.zip";
                    a.style.display = 'none';
                    document.body.appendChild(a);
                    a.click();
                    a.parentElement.removeChild(a);
                }
            };


        xhttp.open("POST", "Form/Download");
        xhttp.setRequestHeader("Content-Type", "application/json");
        xhttp.dataType = "json";
        xhttp.responseType = 'blob';
        xhttp.send(JSON.stringify(organization));

**Comment by dvdobrovolskiy** [comment]
It helps, tnks. Only concern is to definitely call hide somewhere is any error is happened. Or I will end up with p-loading constant running
